trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/*

parameters:
  - name: subscriptionId
    type: string
    default: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'

  - name: svcConnection
    type: string
    default: '[Insert Svc Connection here]'

  - name: location
    type: string
    default: 'Australia East'

variables:
  vmImageName: ubuntu-latest
  templateFolderPath: $(Pipeline.Workspace)/s/bicep
  templateFileBaseName: deploy-infra # File without extension
  parameterFilePath: $(Pipeline.Workspace)/s/bicep/deploy-infra.parameters.bicepparam
  adoEnvironment: "Secrets_Checker"
  deploymentName: "deploy_secrets_management_infra_$(Build.BuildNumber)"

stages:
  - template: /pipelines/templates/build-template.yml@self
    parameters:
      templateFilePath: "$(templateFolderPath)/$(templateFileBaseName).bicep"
      parameterFilePath: "$(parameterFilePath)"
      continueOnFailedTests: true     # arm-ttk not perfect for complex compiled biceps yet
      svcConnection: ${{parameters.svcConnection}}
      testCondition: eq(variables['Build.Reason'], 'PullRequest')

  - template: /pipelines/templates/deploy-template-sub.yml@self
    parameters:
      stage: Deploy_Azure_Infra_Resources
      dependsOn: "Build"
      location: ${{parameters.location}}
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual')))
      adoEnvironment: $(adoEnvironment)
      parameterFilePath: $(parameterFilePath)
      svcConnection: ${{parameters.svcConnection}}
      subscriptionId: ${{parameters.subscriptionId}}
      templateFileName: "$(templateFileBaseName).json"
      deploymentName: $(deploymentName)
      previewChanges: true