name: code_build

on:
  workflow_call:
    inputs:
      function_appcodedir:
        description: The directory where the function app code sits
        type: string
      environment:
          description: "environment for this deployment"
          type: string

env: 
  deployment_name: "deploy_sctmgr_code" # name of the arm deployment"
  build_folder: "build"

jobs:
  build_code:
    runs-on: windows-latest
    steps:
      - name: 'Checkout gitHub action'
        uses: actions/checkout@v3

      - name: Build function app code
        run: |
          if (Test-Path "extensions.csproj") {
            dotnet build extensions.csproj --output ./${{ inputs.function_appcodedir }}/bin
            }

      - name: Compress artifact
        run: |
          mkdir ${{ runner.temp }}/${{ env.build_folder }}
          Compress-Archive -Path ${{ inputs.function_appcodedir }}/* -DestinationPath ${{ runner.temp }}/${{ env.build_folder }}/fa-code.zip

      - name: Publish artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: deploy_code
          path: ${{ runner.temp }}/${{ env.build_folder }}/fa-code.zip