name: Prod Operations - Secrets Checker - Code Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - function-apps/secrets-management/*
  pull_request:
    branches:
      - main
    paths:
      - function-apps/secrets-management/*

env:
  location: "australiaeast" # location for resource deployment in azure
  subscription_id: "e6dffdaa-5ee9-4ea5-9330-1f148f3f2884" # azure subscription id (not required for tenant level deployments)
  oidc_app_reg_client_id: "a1091385-06b9-4f70-ae46-bc38aa29ca44" # client id of the azure application registration used to authenticate to azure using oidc, refer to https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions
  azure_tenant_id: "34846174-e57d-4384-9114-59a7f95fcada" # azure ad tenant/directory id
  environment: "prod" # name of the github environment
  deployment_name: "operations_platform_secrets-checker-code" # name of the arm deployment"
  function_appcodedir: "function-apps/secrets-management"
  function_app_name: "ccv-srt-mgmr-func"
  function_app_rg: "secrets-management-rg"
jobs:
  initialise_vars:
    runs-on: ubuntu-latest
    outputs:
      location: ${{ env.location }}
      subscription_id: ${{ env.subscription_id }}
      oidc_app_reg_client_id: ${{ env.oidc_app_reg_client_id }}
      azure_tenant_id: ${{ env.azure_tenant_id }}
      environment: ${{ env.environment }}
      deployment_name: ${{ env.deployment_name }}
      function_appcodedir: ${{ env.function_appcodedir }}
      function_app_name: ${{ env.function_app_name }}
      function_app_rg: ${{ env.function_app_rg }}
    steps:
      - name: Initialise Variables
        run: echo "Initialising environment variables"


  build_code:
    needs: initialise_vars
    uses: drpebkac/secret-managementr-withkv/.github/workflows/code_build.yml@main
    with:
      function_appcodedir: ${{ needs.initialise_vars.outputs.function_appcodedir }}

  deploy_code:
    needs: [initialise_vars, build_code]
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    uses: drpebkac/secret-managementr-withkv/.github/workflows/code_deploy.yml@main
    with:
      function_app_name: ${{ needs.initialise_vars.outputs.function_app_name }}
      function_app_rg: ${{ needs.initialise_vars.outputs.function_app_rg}}
      environment: ${{ needs.initialise_vars.outputs.environment }}
      subscription_id: ${{ needs.initialise_vars.outputs.subscription_id }}
      oidc_app_reg_client_id: ${{ needs.initialise_vars.outputs.oidc_app_reg_client_id }}
      azure_tenant_id: ${{ needs.initialise_vars.outputs.azure_tenant_id }}
