name: Deploy Infrastructure for Secret Management utility

on:
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  content: read

env:
  template_file_path: bicep/secret-management
  parameter_file_name: deploy-sm-infra.parameters.bicepparam
  